### ISSUE TITLE
Java 8 as requirement?

### ISSUE THREAD

**Issue by Dierk** [Frege/native-gen#11]
It appears the artifacts are compiled with Java 8 as the target version. Is that on purpose? Is Java 8 required?
(The question was originally posted by Ingo on the frege-gradle-plugin project that depends on native-gen)

cheers
Dierk

**Comment by mmhelloworld** [comment]
Java 8 is not a requirement and the native-gen artifact from the releases page seems to have been compiled with Java 7 (major version 51 from the output of `javap`).

**Comment by Dierk** [comment]
hm, have to see where else that comes from...

thanks for checking!
Dierk

**Comment by Ingo60** [comment]
Mark Perry references his own artifact in the gradle plug in. That's why I opened this issue there.

**Comment by mperry** [comment]
I will have a look at this tonight.

**Comment by mperry** [comment]
I addressed the last issue with using Java 7 with #26.
