### ISSUE TITLE
Update release to last version of Frege

### ISSUE THREAD

**Issue by ftomassetti** [Frege/native-gen#5]
Currently I need to install both the current version of Frege and the one used to compile native-gen (it does not work with the newest one).

**Comment by mperry** [comment]
Yes, these look like they are caused by the changes to fixity resolution in the Haskell 2010 report, https://github.com/Frege/frege/wiki/New-or-Changed-Features.  @mmhelloworld Any chance you can look at this?  Should be simple if you know the code.

**Comment by mmhelloworld** [comment]
I just updated with the latest Frege along with other fixes. Sorry, this issue took a long time! I couldn't get a chance to work on this project.
